### ISSUE TITLE
Roll into Liftbridge development story

### ISSUE THREAD

**Issue by tylertreat** [dgzlopes/liftbridge-docker#1]
Wondering what your thoughts are @dgzlopes on promoting this repo into the @liftbridge-io organization and rolling it in as part of the local development story? https://liftbridge.io/docs/deployment.html

cc @annismckenzie

**Comment by dgzlopes** [comment]
Yeah! Sure :)

As I can't directly transfer it to the organization... I transfer it to you and then you move it into the organization?

**Comment by annismckenzie** [comment]
Yeah, that would be awesome. I added a Makefile target using a skaffold profile to build and push the image in https://github.com/liftbridge-io/liftbridge/pull/130/files#diff-b67911656ef5d18c4ae36cb6741b7965R13.

**Comment by annismckenzie** [comment]
Mind you, there need to be two images for non-k8s and k8s. 😅

**Comment by tylertreat** [comment]
> As I can't directly transfer it to the organization... I transfer it to you and then you move it into the organization?

Not actually sure. I think if you add me to the repo I can transfer it to the org?

**Comment by tylertreat** [comment]
I probably need to be an admin on it.

**Comment by dgzlopes** [comment]
It looks like for repositories owned by a user account I can't make that! I sent you a transfer request :) You should be able to move it to the org.

**Comment by tylertreat** [comment]
Repo has been transferred to @liftbridge-io: https://github.com/liftbridge-io/liftbridge-docker

@dgzlopes I also made you a maintainer on the repo. I'll work on updating the [documentation](https://liftbridge.io/docs/deployment.html) to include this.
