### ISSUE TITLE
Automate container build/tag/push

### ISSUE THREAD

**Issue by dgzlopes** [dgzlopes/liftbridge-docker#2]
> Leaving this issue here as a reminder. 

When the main Liftbridge repo starts to use the tag/release feature, we should automate the build/tag/push process of this container (with CircleCI/TravisCI to Docker Hub and/or Github Packages).

**Comment by tylertreat** [comment]
Closing this issue as we are now automatically tagging and pushing dev images on master: https://github.com/liftbridge-io/liftbridge/blob/4efdd32b1b824749a017895f3bc43753f441f906/.circleci/config.yml#L74-L80
